# 网站logo
logo: https://p.pstatp.com/origin/ffe10002f518b2105736

# 头像
avatar: https://p.pstatp.com/origin/13739000358e9eca58439

# 首页自定义(文字&图片)
# 文字
homebutton: 少女祈祷中 ~
homewz1: 星期四・沉迷幻想
homewz2: 世界犹如一面镜子 ：朝它皱眉它就朝你皱眉，朝它微笑它也朝你微笑
homewz3: The world is like a mirror ： Frown at itand it frowns at you; smile, and it smiles too

# 图片

hometupian: https://p.pstatp.com/origin/ff30000270f5b44ee2f8